version: "3.8"

services:
  api:
    image: alfonsofr.azurecr.io/api:ci
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_ARTIFACT_PATH=${WANDB_ARTIFACT_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 3s
      retries: 5