services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      -"8000:8000"
    environment:
      - API_PORT: 8000
      - WANDB_API_KEY: ${WANDB_API_KEY}
      - WANDB_ARTIFACT_PATH: ${WANDB_ARTIFACT_PATH}
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  capture:
    image: capture:latest
    build:
      context: ./capture
      dockerfile: Dockerfile
    env_file:
      - .env
  train:
    image: train:latest
    build:
      context: ./train
      dockerfile: Dockerfile
    ports:
      -"8000:8000"
    environment:
      - API_PORT: 8000
      - WANDB_API_KEY: ${WANDB_API_KEY}
      - WANDB_ARTIFACT_PATH: ${WANDB_ARTIFACT_PATH}
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s