version: "3.3"
services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
  capture:
    image: capture:latest
    build:
      context: ./capture
      dockerfile: Dockerfile
  train:
    image: train:latest
    build:
      context: ./train
      dockerfile: Dockerfile