version: "3.3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api:latest
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    working_dir: /app
    volumes:
      - ./api:/app

  capture:
    build:
      context: ./capture
      dockerfile: Dockerfile
    image: capture:latest
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./capture:/app
      - ./images:/app/images
      - ./yolo_dataset:/app/yolo_dataset
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true

  train:
    image: train:latest
    build:
      context: ./train
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env