version: "3.8"

services:
  api:
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env

  web:
    image: web:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    env_file:
      - .env