name: CI/CD for Develop Branch
on: 
  push:
    branches:
      - develop

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v3
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - '/src/api/**'

# ----------------- BUILD API ------------------
  build-api:
    runs-on: ubuntu-latest
    needs: [detect-changes]
    if: ${{needs.detect-changes.outputs.api == 'true'}}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker login
        run: az acr login --name ${{ vars.AZURE_ACR_NAME }}
      - name: Build and push API image
        run: |
          docker build -t ${{ vars.AZURE_ACR_NAME}}.azurecr.io/api:ci ./src/api
          docker push ${{ vars.AZURE_ACR_NAME}}.azurecr.io/api:ci

# ----------------- DEPLOY ------------------
  deploy:
    runs-on: ubuntu-latest
    needs: [build-api]
    if: ${{ always() && (needs.build-api.result == 'success') }}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Prepare docker-compose.prod.yml
        run: |
          cd /src
          cp docker-compose.prod.yml docker-compose.yml
          zip deploy.zip docker-compose.yml
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: /src/deploy.zip